version: "2.28.1-desktop.1d"
services:
  postgres:
    image: postgres:16.3
    container_name: postgres_container
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Task_management_system_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: app
    container_name: app_container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
